parameters:
#    cart_shop_cart.example.class: Cart\ShopCartBundle\Example

services:
#    cart_shop_cart.example:
#        class: %cart_shop_cart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
